name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/hbjwjzsj60xou9mwn6clz/520b68dc-589e-11f1-8336-58ce2aade9b3.zip?rlkey=rrocnolj7z08rcd92jxwenllc&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project TADC Alpha  B1.xcodeproj -scheme 'TADC Alpha  B1' -archivePath TADC Alpha  B1.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv TADC Alpha  B1.xcarchive/Products/Applications/TADC Alpha  B1.app Payload/TADC Alpha  B1.app

          zip -r "TADC Alpha  B1.ipa" "Payload"

          mv TADC Alpha  B1.ipa ${{ runner.temp }}/TADC Alpha  B1.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: TADC Alpha  B1
          path: ${{ runner.temp }}/TADC Alpha  B1.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3