name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/hfqcgf1kd4w979pqan7f9/332baee6-58a7-11f1-a15a-58ce2aade9b3.zip?rlkey=d2lquot3osovmgjex0dwnsew3&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project TADC.xcodeproj -scheme 'TADC' -archivePath TADC.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv TADC.xcarchive/Products/Applications/TADC.app Payload/TADC.app

          zip -r "TADC.ipa" "Payload"

          mv TADC.ipa ${{ runner.temp }}/TADC.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: TADC
          path: ${{ runner.temp }}/TADC.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3